FROM @@FROM@@

#ENV TZ=Europe/Paris
#RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update && \
    apt-get install -y eatmydata && \
    eatmydata apt-get upgrade -y && \
    eatmydata apt-get install -y \
                       gosu sudo locales vim curl wget \
                       build-essential git bin86 bcc lzma liblzma-dev \
                       python3 python3-dev python3-venv acpica-tools uuid-dev \
                       libncurses-dev pkg-config libglib2.0-dev \
                       libpixman-1-dev libyajl-dev libsystemd-dev \
                       bison flex ocaml-findlib libnl-3-dev libnl-route-3-dev \
                       cmake libjson-c-dev libcmocka-dev ninja-build nasm \
                       bash-completion

RUN sed -i 's/# en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/' /etc/locale.gen && \
    locale-gen
ENV LANG=en_US.UTF-8

# Let's just have /bin/sh as bash
RUN echo "dash dash/sh boolean false" | debconf-set-selections && \
    dpkg-reconfigure dash

COPY entrypoint.sh /usr/bin/entrypoint.sh
COPY bash_profile /etc/skel/.bash_profile
RUN chmod +x /usr/bin/entrypoint.sh

ENTRYPOINT [ "/usr/bin/entrypoint.sh" ]
CMD [ "/bin/bash", "-l" ]
